<?php

namespace AppBundle\Repository;

/**
 * smCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smCityRepository extends \Doctrine\ORM\EntityRepository
{
}
