<?php

namespace AppBundle\Repository;

/**
 * smCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
