<?php

namespace AppBundle\Repository;

/**
 * smOrderServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smOrderServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
