<?php

namespace AppBundle\Repository;

/**
 * smOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
