<?php

namespace AppBundle\Repository;

/**
 * smServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
