<?php

namespace AppBundle\Repository;

/**
 * smTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
