<?php

namespace AppBundle\Repository;

/**
 * smUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smUserRepository extends \Doctrine\ORM\EntityRepository
{
}
