<?php

namespace AppBundle\Repository;

/**
 * smUserServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class smUserServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
